import { test, expect } from '@playwright/test'

test('server creation, persistence, search, edit and deletion', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('从第一台服务器开始')).toBeVisible()
  await page.getByRole('button', { name: '添加服务器', exact: true }).last().click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('东京 · 主节点')
  await dialog.getByLabel('分组', { exact: true }).fill('生产环境')
  await dialog.getByLabel('主机', { exact: true }).fill('192.0.2.10')
  await expect(dialog.getByLabel('SSH 密码', { exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: '添加服务器', exact: true }).click()
  await expect(page.getByRole('heading', { name: '东京 · 主节点' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '东京 · 主节点' })).toBeVisible()
  await page.getByPlaceholder('搜索服务器…').fill('nothing-matches')
  await expect(page.getByText('没有找到服务器')).toBeVisible()
  await page.getByRole('button', { name: '清除搜索' }).click()
  await page.getByRole('button', { name: '连接', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请在桌面应用中连接 SSH')
  await page.getByRole('button', { name: '管理 东京 · 主节点' }).click()
  await page.getByRole('button', { name: '编辑服务器', exact: true }).click()
  await dialog.getByLabel('名称', { exact: true }).fill('东京 · 备用节点')
  await dialog.getByRole('button', { name: '保存更改' }).click()
  await expect(page.getByRole('heading', { name: '东京 · 备用节点' })).toBeVisible()
  await page.getByRole('button', { name: '管理 东京 · 备用节点' }).click()
  await page.getByRole('button', { name: '删除服务器', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '删除服务器' }).click()
  await expect(page.getByText('从第一台服务器开始')).toBeVisible()
  expect(errors).toEqual([])
  expect(await page.evaluate(() => localStorage.getItem('s-ui-hub.preview.servers.v1'))).not.toContain(
    'password',
  )
})

test('workspace supports all four layouts and selecting empty panels', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '面板工作区', exact: true }).click()
  await expect(page.locator('.pane')).toHaveCount(1)
  await page.getByRole('button', { name: '左右分屏', exact: true }).click()
  await expect(page.locator('.pane')).toHaveCount(2)
  await page.getByRole('button', { name: '上下分屏', exact: true }).click()
  await expect(page.locator('.panes')).toHaveClass(/layout-rows/)
  await page.getByRole('button', { name: '四宫格', exact: true }).click()
  await expect(page.locator('.pane')).toHaveCount(4)
  await page.getByRole('button', { name: '连接服务器', exact: true }).nth(3).click()
  await expect(page.getByRole('dialog')).toContainText('先添加一台服务器')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '收起侧栏' }).click()
  await expect(page.locator('.sidebar')).toBeHidden()
  await page.setViewportSize({ width: 960, height: 640 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('workspace shortcut switches views with the sidebar collapsed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '收起侧栏' }).click()
  const trigger = page.locator('.workspace-trigger')
  const navigation = page.getByRole('navigation', { name: '快捷切换', exact: true })
  await expect(trigger).toHaveText('全部服务器')
  await trigger.click()
  await navigation.getByRole('button', { name: '已连接', exact: true }).click()
  await expect(page.getByRole('heading', { name: '已连接的服务器' })).toBeVisible()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(trigger).toHaveText('已连接')
  await trigger.click()
  await navigation.getByRole('button', { name: '面板工作区', exact: true }).click()
  await expect(page.locator('.pane')).toHaveCount(1)
  await expect(trigger).toHaveText('面板工作区')
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(navigation).toHaveCount(0)
  await trigger.click()
  await navigation.getByRole('button', { name: '全部服务器', exact: true }).click()
  await expect(page.getByRole('heading', { name: '我的服务器' })).toBeVisible()
  await trigger.click()
  await page.locator('.connection-count').click()
  await expect(navigation).toHaveCount(0)
})
